### ISSUE TITLE
Roblox Studio Camera is bugged.

### ISSUE THREAD

**Issue by zleeepy** [vinegarhq/vinegarhq.github.io#138]
On roblox studio, the camera is completely broken. It spins like crazy everywhere, and is a pain to control. Switching to X11 dosnt fix the issue.

**Comment by AlcyonX** [comment]
> On roblox studio, the camera is completely broken. It spins like crazy everywhere, and is a pain to control. Switching to X11 dosnt fix the issue.

I have the same issue on arch linux with hyprland...

**Comment by adverbialsatz** [comment]
If you're on flatpak download and extract proton ge and just make the extracted folder the wineroot in the config. If you're on something else than flatpak, download umu-launcher as well and put this 
```toml
[studio.env]
PROTONPATH = "/path/to/proton"
GAMEID = "0"
PROTON_VERB = "run"
```
in your config as well
